services:
  # PostgreSQL: Untuk Data Relasional (Users, Enrollments, Payments)
  postgres:
    image: postgres:15-alpine
    container_name: lms-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: lms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # MongoDB: Untuk Content (Courses, Lessons, Quizzes)
  mongodb:
    image: mongo:latest
    container_name: lms-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Redis: Untuk Cache & Real-time (Sessions, Leaderboard)
  redis:
    image: redis:7-alpine
    container_name: lms-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data: